### ISSUE TITLE
Update Paths / Content Structure for Practices

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/practice-library#7]
Practices should be under "practices", not routes. Routes are a collection of practices aligned to a specific labs journey.

e.g. https://rht-labs.github.io/practice-library/routes/realtime-retrospective/ should be https://rht-labs.github.io/practice-library/practices/realtime-retrospective/

**Comment by rdebeasi** [comment]
The latest version of the site implements this feedback. Feel free to re-open or open a new issue if there's other stuff that you'd like to see! :smile:
