### ISSUE TITLE
implement a search capability 

### ISSUE THREAD

**Issue by mtakane** [rht-labs/practice-library#8]
As a facilitator or a practitioner, I sometimes find myself knowing generally what I am looking for, but not exactly. I need some way to find what i'm looking for with some key terms, so that I can quickly get to the page I am looking for.

Want to be able to search from any of the pages for any of the content. should be able to search through the actual content of the page, and ensure that tagging is taken into account as well.

**Comment by rdebeasi** [comment]
We now have search! Closing.
