### ISSUE TITLE
Add Realtime Retrospectives

### ISSUE THREAD

**Issue by valyonchev** [rht-labs/practice-library#83]

**Comment by tdbeattie** [comment]
@valyonchev The Realtime Retrospective is already live https://rht-labs.github.io/practice-library/practices/realtime-retrospective/ so I'll close this.

Feel free to raise pull request if you want to expand on the content that's been written.

**Comment by valyonchev** [comment]
Ahh, missed it. I hope to have some time in the next few weeks to start writing up on some of the practices.
