### ISSUE TITLE
FIX broken link Event Storming

### ISSUE THREAD

**Issue by cheekymuppet** [rht-labs/practice-library#95]
On the Event Storming page <<[here](https://rht-labs.github.io/practice-library/practices/event-storming/)>> there is a broken link to User Story Mapping in the Related Practices section

**Comment by rdebeasi** [comment]
Confirmed. The correct URL is https://rht-labs.github.io/practice-library/practices/user-story-mapping/.

Thanks for catching this! :smile:

**Comment by tdbeattie** [comment]
PR raised - PR raised - https://github.com/rht-labs/practice-library/pull/99

**Comment by rdebeasi** [comment]
Resolved.
