### ISSUE TITLE
Add 12-month goal setting and key questions

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/practice-library#96]
https://www.thesprintbook.com/

**Comment by rdebeasi** [comment]
Is there a specific practice or idea from the book that you'd like to add? To me, the sprint book is almost like its own practice library.

**Comment by sherl0cks** [comment]
12 month goal setting and key questions, which is the very beginning of Monday in the book.

**Comment by rdebeasi** [comment]
Cool! For clarity's sake, can we make that the title of this issue (and the associated practice)?

**Comment by sherl0cks** [comment]
Sure, update how you see fit
