### ISSUE TITLE
Social Contract link return 404

### ISSUE THREAD

**Issue by noelo** [rht-labs/practice-library#97]
On Page https://rht-labs.github.io/practice-library/practices/social-contract/ the following link is not found https://www.scrumalliance.org/community/articles/2014/january/work-agreements-scrum-team

It might be a temporary issue.

**Comment by rdebeasi** [comment]
Thank you for reporting this issue! I'm also getting that error:

> This article is currently not available.  We apologize for the inconvenience.  Please check back again later.

The message does sound like a temporary issue, but as far as I can tell, it pops up for any "not found" error. I think the correct URL is: https://www.scrumalliance.org/community/articles/2014/january/work-agreements-for-a-scrum-team

**Comment by tdbeattie** [comment]
PR raised - https://github.com/rht-labs/practice-library/pull/99

**Comment by rdebeasi** [comment]
Resolved.
